version: '3'
services:
  database:
    image: postgis/postgis:13-master
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD_FILE: '/run/secrets/database_password'
      POSTGRES_DB: 'directus'
    secrets:
      - database_password

  cache:
    image: redis:6

  directus:
    image: directus/directus:10.4.0
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
    depends_on:
      - cache
      - database
    environment:
      PUBLIC_URL: 'https://www.monserverdirectus.com'
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET_FILE: '/run/secrets/directus_secret'
      LOG_LEVEL: 'error'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD_FILE: '/run/secrets/database_password'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD_FILE: '/run/secrets/directus_admin_password'

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: 'https://directus.example.com'
    secrets:
      - database_password
      - directus_secret
      - directus_admin_password

secrets:
  database_password:
    file: ./secrets/database_password.txt
  directus_secret:
    file: ./secrets/directus_secret.txt
  directus_admin_password:
    file: ./secrets/directus_admin_password.txt